"""add_performance_indexes

Revision ID: f4c3f5632753
Revises: 1651277d2d3e
Create Date: 2026-09-13 11:24:54.668722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c3f5632753'
down_revision: Union[str, None] = '1651277d2d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_case_id'), 'audit_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_created_by'), 'cases', ['created_by'], unique=False)
    op.create_index(op.f('ix_cases_risk_level'), 'cases', ['risk_level'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_case_id'), 'extracted_fields', ['case_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_document_id'), 'extracted_fields', ['document_id'], unique=False)
    op.create_index(op.f('ix_reviews_case_id'), 'reviews', ['case_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.drop_index(op.f('ix_users_google_subject'), table_name='users')
    op.drop_column('users', 'google_subject')
    op.create_index(op.f('ix_verification_results_case_id'), 'verification_results', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_results_case_id'), table_name='verification_results')
    op.add_column('users', sa.Column('google_subject', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_google_subject'), 'users', ['google_subject'], unique=True)
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_case_id'), table_name='reviews')
    op.drop_index(op.f('ix_extracted_fields_document_id'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_case_id'), table_name='extracted_fields')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_risk_level'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_by'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_case_id'), table_name='audit_logs')
    # ### end Alembic commands ###
